env:
  global:
    - PIP_URL="https://bootstrap.pypa.io/get-pip.py"
    - PIP="python -m pip"

matrix:
  fast_finish: true
  include:
    - os: osx
      language: generic
      env:
        - NAME="Python 2.6"
        - PIP_URL="https://bootstrap.pypa.io/2.6/get-pip.py"
        - PIP=pip
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install 2.6.9
        - pyenv local 2.6.9
        - eval "$(pyenv init -)"
        - pip install virtualenv
        - python2.6 -m virtualenv env
        - pyenv local --unset
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python 2.7"
      before_install:
        - brew update
        - brew upgrade python2 || true
        - python2.7 -m pip install virtualenv
        - python2.7 -m virtualenv env
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python pypy"
      before_install:
        - brew update
        - brew upgrade pypy || brew install pypy || true
        - pypy -m pip install virtualenv
        - pypy -m virtualenv env
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python 3.4"
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install 3.4.9
        - pyenv local 3.4.9
        - eval "$(pyenv init -)"
        - python3.4 -m venv env
        - pyenv local --unset
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python 3.5"
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install 3.5.6
        - pyenv local 3.5.6
        - eval "$(pyenv init -)"
        - python3.5 -m venv env
        - pyenv local --unset
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python 3.6"
      before_install:
        - brew update
        - brew upgrade pyenv || brew install pyenv || true
        - pyenv install 3.6.6
        - pyenv local 3.6.6
        - eval "$(pyenv init -)"
        - python3.6 -m venv env
        - pyenv local --unset
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python 3.7"
      before_install:
        - brew update
        - brew upgrade python || true
        - python3.7 -m venv env
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python HEAD"
      before_install:
        - brew update
        - brew unlink python
        - brew install python --HEAD
        - python3 -m venv env
        - source env/bin/activate
    - os: osx
      language: generic
      env: NAME="Python pypy3"
      before_install:
        - brew update
        - brew upgrade pypy3 || brew install pypy3 || true
        - pypy3 -m venv env
        - source env/bin/activate
    - os: linux
      env:
        - PIP_URL="https://bootstrap.pypa.io/2.6/get-pip.py"
        - PIP=env/bin/pip
      language: python
      python: 2.6
      before_install:
        - pip install virtualenv
        - python2.6 -m virtualenv env
        - source env/bin/activate
    - os: linux
      language: python
      python: 2.7
      before_install:
        - pip install virtualenv
        - python2.7 -m virtualenv env
        - source env/bin/activate
    - os: linux
      language: python
      python: pypy
      before_install:
        - pip install virtualenv
        - pypy -m virtualenv env
        - source env/bin/activate
    - os: linux
      language: python
      python: 3.4
      before_install:
        - python3.4 -m venv env
        - source env/bin/activate
    - os: linux
      language: python
      python: 3.5
      before_install:
        - python3.5 -m venv env
        - source env/bin/activate
    - os: linux
      language: python
      python: 3.6
      before_install:
        - python3.6 -m venv env
        - source env/bin/activate
    - os: linux
      language: python
      python: &python_major_ver 3.7
      dist: xenial
      sudo: true
      before_install:
        - python3.7 -m venv env
        - source env/bin/activate
    - os: linux
      language: python
      python: 3.6-dev
      before_install:
        - python3.6 -m venv env
        - source env/bin/activate
    - os: linux
      language: python
      python: 3.7-dev
      before_install:
        - python3.7 -m venv env
        - source env/bin/activate
    - os: linux
      language: python
      python: nightly
      before_install:
        - python3 -m venv env
        - source env/bin/activate
    - os: linux
      language: python
      python: pypy3
      before_install:
        - pypy3 -m venv env
        - source env/bin/activate
  allow_failures:
    - os: osx
      env: NAME="Python HEAD"
    - os: linux
      python: 3.6-dev
    - os: linux
      python: 3.7-dev
    - os: linux
      python: nightly

install:
  - which python
  - ls env/bin
  - curl ${PIP_URL} | python
  - ${PIP} install -r requirements.txt

script:
  - python setup.py test

after_success:
  - python -m codecov
